# Maubot Sonos plugin base configuration

whitelist:
  - '@alice:example.com'         # spesific user
  - ':example.com'                 # all on example.com homeserver
  - '^@[^:]+:example\.cp,$'        # regex all @user:example.com
